baseURL = "https://danielmrcl.dev"
languageCode = "en-us"
title = "Daniel Jr | Backend Developer"
theme = "cactus"
copyright = "Me"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[markup]
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "gruvbox"
tabWidth = 4

[params]
colortheme = "dark"
rss = false
tocInline = true
logo = "image.jpg"
favicon = "favicon.ico"
description = "Since 2021 I have been developing web services in microservice architecture for critical, efficient, and scalable systems. I also love Linux, cloud, cli-tools, hardware, and all about computers."
tagsOverview = true
showProjectsList = true
show_updated = true
showReadTime = false

[params.comments]
enabled = false

[[params.social]]
name = "email"
link = "dan@danielmrcl.dev"
[[params.social]]
name = "linkedin"
link = "https://click.danielmrcl.dev/linkedin-cmMJ"
[[params.social]]
name = "github"
link = "https://click.danielmrcl.dev/github-eeW7"
[[params.social]]
name = "medium"
link = "https://click.danielmrcl.dev/medium-qz5w"
