baseURL = "https://danielmrcl.dev"
languageCode = "en-us"
title = "Daniel Jr | Backend Developer"
theme = "cactus"
copyright = "Me"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "https://medium.com/@danielmrcl"
weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "gruvbox"
    tabWidth = 4

[params]
  colortheme = "dark"
  rss = false
  tocInline = true
  logo = "image.jpg"
  favicon = "favicon.ico"
  description = "Since 2021, I've been developing Java web services using Spring and PostgreSQL in a microservices architecture for critical, efficient and scalable systems."
  tagsOverview = true
  showProjectsList = true
  show_updated = true
  showReadTime = false

  [params.comments]
    enabled = false

  [[params.social]]
    name = "github"
    link = "https://github.com/danielmrcl"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/danielmrcl/"
  [[params.social]]
    name = "email"
    link = "dan@danielmrcl.dev"
